// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArUg42w4MLiBfw0hmqJNBIJIezYqgql9M',
    appId: '1:491599307332:web:188664609f9860992f5211',
    messagingSenderId: '491599307332',
    projectId: 'practice-mother-fucker',
    authDomain: 'practice-mother-fucker.firebaseapp.com',
    storageBucket: 'practice-mother-fucker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOotzArdoClmn_1spDeF9SPUjE2RtzfLY',
    appId: '1:491599307332:android:6193735cc8a11dbf2f5211',
    messagingSenderId: '491599307332',
    projectId: 'practice-mother-fucker',
    storageBucket: 'practice-mother-fucker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6dMTzV8yioNscDVfc8pBq3xBWXRmmAt0',
    appId: '1:491599307332:ios:18f68abf35aa54812f5211',
    messagingSenderId: '491599307332',
    projectId: 'practice-mother-fucker',
    storageBucket: 'practice-mother-fucker.appspot.com',
    androidClientId: '491599307332-31ltljleuik640ai7viilpprj8cm5nh5.apps.googleusercontent.com',
    iosClientId: '491599307332-pga1ct8a8u5tf0k5lqbsf3uojijv1ocn.apps.googleusercontent.com',
    iosBundleId: 'com.example.lotOfPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6dMTzV8yioNscDVfc8pBq3xBWXRmmAt0',
    appId: '1:491599307332:ios:eef3747c2f67e5e82f5211',
    messagingSenderId: '491599307332',
    projectId: 'practice-mother-fucker',
    storageBucket: 'practice-mother-fucker.appspot.com',
    androidClientId: '491599307332-31ltljleuik640ai7viilpprj8cm5nh5.apps.googleusercontent.com',
    iosClientId: '491599307332-ncheg6eugha0cqoshc5qefuo1nknrdaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.lotOfPractice.RunnerTests',
  );
}
